---
title: "Professional Career"
format: html
css: www/custom.css
---

# Grupo Amigão - Pricing Data Analyst

#### ● Dec 2025 - Present

I currently work as a Pricing Data Analyst at Grupo Amigão, where I develop and enhance analytical pricing models focused on price elasticity, profitability, and competitiveness in the retail and wholesale sector. My role involves conducting market and competitor price analyses, monitoring key performance indicators (KPIs), and identifying patterns in large datasets to generate actionable business insights. I actively support pricing architecture and assortment strategies, balancing competitiveness with customer value perception. 

Additionally, I perform pricing simulations and scenario analyses including regular pricing, promotions, and markdowns—while collaborating closely with teams such as Commercial, Marketing, Supply Chain, and Market Intelligence. I also contribute to the technological evolution of the pricing area through the use of BI tools, dashboards, automation, and data-driven decision-making.

------------------------------------------------------------------------

# Oper - Data Analyst/Engineer

#### ● Mar 2024 - Aug 2025 (1 year and 6 months)

I worked as a Data Analyst and Data Engineer in multidisciplinary teams, analyzing large volumes of data to support data-driven decision-making. I designed and optimized pipelines to improve accessibility and processing efficiency, including enhancing an ETL pipeline in Databricks with SQL and PySpark that achieved a 1500% performance gain.

I developed and maintained dozens of interactive dashboards and reports for national and international clients, contributing to over R\$2.5 million in gross profit and supporting sustainable business growth. I used technologies such as R, Python, SQL, Azure Databricks, PySpark, Excel, and Shiny to create analyses, reports, dashboards, and ETL pipelines.

------------------------------------------------------------------------

# Kreativstorm - Data Analyst Trainee

#### ● Aug 2023 - Sep 2023 (2 months)

I collaborated with a diverse team of data analysts and students from around the world on complex case studies analyzing household behavior in the UK. During this experience, I enhanced my proficiency in R and Python by applying theoretical knowledge to practical scenarios, while also improving my spoken and written English through teamwork and presentations, which strengthened my ability to communicate effectively in an international setting.
